# Generated by Django 6.0.3 on 2026-03-04 07:02

from django.db import migrations


def create_extension(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS vector;")

def drop_extension(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("DROP EXTENSION IF EXISTS vector;")


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_document_mime_type_document_sha256_and_more'),
    ]

    run_before = [
        ('education', '0013_knowledgesource_knowledgechunk'),
    ]

    operations = [
        migrations.RunPython(create_extension, drop_extension)
    ]
