# Generated by Django 6.0.4 on 2026-05-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0015_ieltstest_ieltsquestion_ieltsattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ieltstest',
            name='section',
            field=models.CharField(choices=[('listening', 'IELTS Listening'), ('reading', 'IELTS Reading'), ('writing', 'IELTS Writing'), ('speaking', 'IELTS Speaking'), ('tolc_math', 'TOLC Mathematics'), ('tolc_logic', 'TOLC Logic'), ('tolc_verbal', 'TOLC Verbal Comprehension'), ('tolc_science', 'TOLC Science')], max_length=20, unique=True),
        ),
    ]
